# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1d5509c71de34037ae2b6e382f90399b61f4ab88ca8c64f43b197c3f03b44522c052f1c85d1825697e17e5cc8441a533414450c832ba190aa1b162a4b2113b

test:
  secret_key_base: f2052d73eb33b06778e1a359411b6f1677434832eda0271e624bf09815059bf82f233af2b9837e669646be40a32139f1d64c7b7ce09201f8a309711b7b8743e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
